Feature/vault
VenusProtocol/venus-protocol pull request #66
Opened 2021-09-15 11:08 UTC by ferrari105

## Description

As the XVS vault branch, this has following features:

## Checklist

- [ ] I have updated the documentation to account for the changes in the code.
- [x] If I added new functionality, I added tests covering it.
- [ ] If I fixed a bug, I added a test preventing this bug from silently reappearing again.
- [ ] My contribution follows [Venus contribution guidelines](docs/CONTRIBUTING.md).

2021-09-16 12:14 UTC, kkirka requested changes
I left several comments there, these should be addressed. I'll make another pass a bit later.

2021-09-16 12:14 UTC, kkirka commented on tests/XVSVault/xvsVaultProxyTest.js
> +      // XXX TODO?
Are you going to add this test?

2021-09-16 12:14 UTC, kkirka commented on tests/XVSVault/xvsVaultProxyTest.js
> +      });
Same for these two — do you plan to complete them?

2021-09-16 12:14 UTC, kkirka commented on contracts/XVSVault/XVSVault.sol
> +    }
This function just returns the user's XVS balance in the vault, not the voting power, is this supposed to be changed in the governance PR?

2021-09-16 12:14 UTC, kkirka commented on contracts/XVSVault/XVSVault.sol
> +    function ExecuteWithdrawal(address _rewardToken, uint256 _pid) public nonReentrant {
Why does it start with an uppercase letter though, any particular reason for this?

```suggestion
    function executeWithdrawal(address _rewardToken, uint256 _pid) public nonReentrant {
```

2021-09-16 12:14 UTC, kkirka commented on contracts/XVSVault/XVSVault.sol
> +    function RequestWithdrawal(address _rewardToken, uint256 _pid, uint256 _amount) public nonReentrant {
Same here

```suggestion
    function requestWithdrawal(address _rewardToken, uint256 _pid, uint256 _amount) public nonReentrant {
```

2021-09-29 10:52 UTC, gryincent reviewed
1. users can make several withdrawal request.
2. we should use storage update commands before real token transfer, although there is reentrancy check.
@ferrari105 please consider these changes.

2021-09-29 10:52 UTC, gryincent commented on contracts/XVSVault/XVSVault.sol
> +        withdrawal.amount = 0;
@ferrari105 please use this statement before token transfer.

2021-09-29 10:52 UTC, gryincent commented on contracts/XVSVault/XVSVault.sol
> +        user.rewardDebt = user.amount.mul(pool.accRewardPerShare).div(1e12);
we need to update the calculation before reward transfer. @ferrari105

2021-09-29 10:52 UTC, gryincent commented on contracts/XVSVault/XVSVault.sol
> +        require(withdrawal.amount == 0, "request again after execute");
users can make several withdrawal request. we need to update some workflows and storages to implement this. @ferrari105

2021-11-01 12:52 UTC, kkirka approved these changes

2022-01-18 07:20 UTC, merged